baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'KatApp User Documentation'

[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
home = [ "HTML", "RSS"]
